server:
   port: 8888
spring:
   application:
      name: cloud-config
   cloud:
      config:
         server:
            git:
               #uri: https://naxon77@bitbucket.org/naxon77/cloud-config.git
               #username: naxon77
               #password: ysjung96#
               uri: https://github.com/ysjung96/cloud-config.git
               search-paths: misc
               username: ysjung96
               password: nihill96$$